### ISSUE TITLE
Very slow writing to temp file in docker

### ISSUE THREAD

**Issue by ryan0n** [FauxFaux/quad-image#18]
Hi, this project is very cool - thanks for creating it. I recently ditched IRC Cloud for The Lounge and was looking for something to replace the image sharing feature and this fits perfectly. But I've had an issue that I haven't been able to understand or fix when running this in docker. I've tried using the rust base image, alpine, and ubuntu bionic. It gets to [this line](https://github.com/FauxFaux/quad-image/blob/master/src/ingest.rs#L121) and then takes 2+ minutes to finish writing 400kb to the temp file. I was hoping you had a guess as to why. It works without this issue running outside of a docker container.

**Comment by FauxFaux** [comment]
Interesting!

First guess: you're writing to a docker layer, instead of a docker volume mounted over the data directory? Or you're using one of docker's built in volume types, instead of a host directory, which is probably appropriate here? Docker really hates writing to layers.

What host OS are you using? What volume type, or none?

Second guess: There's a problem with https://github.com/FauxFaux/tempfile-fast-rs interacting with docker. This is a library I wrote (although it uses standard unix stuff), the uncommon unix stuff probably isn't well tested in docker. You could try dropping in `tempfile::NamedTemporaryFile` instead?

I'll see if I can reproduce.

**Comment by ryan0n** [comment]
Here's the Dockerfile:

`FROM ubuntu:bionic

RUN apt-get update && apt-get install -y curl bash nodejs git make \
        && curl -sL https://deb.nodesource.com/setup_14.x | bash \
        && apt-get install -y nodejs cargo \
        && git clone https://github.com/FauxFaux/quad-image.git

WORKDIR /quad-image

RUN make

## Replace default listening address address (127.0.0.1) to one that works in this container (0.0.0.0)
RUN sed -i -e 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/0.0.0.0/g' /quad-image/src/main.rs

RUN cargo build --release
#
RUN cp /quad-image/target/release/quad-image /quad-image/quad-image

CMD ["./quad-image"]`

And the docker-compose.yml:


`version: "3.8"
services:
  quad-image:
    build:
      context: ./quad-image
    container_name: quad-image
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    restart: unless-stopped
    ports:
      - 42594:6699
    volumes:
      - ./quad-image/data/uploaded_images:/quad-image/e/`

**Comment by ryan0n** [comment]
[Here](is the docker-compose.yml) and the [Dockerfile](https://gist.github.com/ryan0n/0abb25da57a335be03a566a4a0e8c493) I'm using.

**Comment by ryan0n** [comment]
The issue wound up being writing to the mounted "e", I changed it to write to a "t" dir first, then copy into "e" when it completes. It runs quite fast now.
